import './globals.css';
import Navbar from './components/Navbar';
import DesktopNavbar from './components/DesktopNavbar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <DesktopNavbar />
        {children}
      </body>
    </html>
  );
}
